[project]
name = "Humanism"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipython>=8.37.0",
    "pip>=25.2",
    "seaborn",
    "pandas",
    "numpy",
    "ipykernel>=6.30.1",
    "openpyxl>=3.1.5",
]
